src/Entity/Announcement.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AnnouncementRepository")
 */
class Announcement
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\Column(type="integer")
     */
    private $Price;

    /**
     * @ORM\Column(type="datetime")
     */
    private $PublishedDate;

    /**
     * @ORM\Column(type="text")
     */
    private $Description;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="announcements")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Picture", mappedBy="announcement", cascade="remove")
     */
    private $pictures;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\City", inversedBy="announcements")
     * @ORM\JoinColumn(nullable=false)
     */
    private $city;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="announcements")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\User", mappedBy="favorite")
     */
    private $users;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adress;

    public function __construct()
    {
        $this->pictures = new ArrayCollection();
        $this->users = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->Price;
    }

    public function setPrice(int $Price): self
    {
        $this->Price = $Price;

        return $this;
    }

    public function getPublishedDate(): ?\DateTimeInterface
    {
        return $this->PublishedDate;
    }

    public function setPublishedDate(\DateTimeInterface $PublishedDate): self
    {
        $this->PublishedDate = $PublishedDate;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection|Picture[]
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    public function addPicture(Picture $picture): self
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures[] = $picture;
            $picture->setAnnouncement($this);
        }

        return $this;
    }

    public function removePicture(Picture $picture): self
    {
        if ($this->pictures->contains($picture)) {
            $this->pictures->removeElement($picture);
            // set the owning side to null (unless already changed)
            if ($picture->getAnnouncement() === $this) {
                $picture->setAnnouncement(null);
            }
        }

        return $this;
    }

    public function getCity(): ?City
    {
        return $this->city;
    }

    public function setCity(?City $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->addFavorite($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->contains($user)) {
            $this->users->removeElement($user);
            $user->removeFavorite($this);
        }

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function __toString()
    {
        return (string)$this->Name;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Firstname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Announcement", mappedBy="user")
     */
    private $announcements;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Announcement", inversedBy="users")
     */
    private $favorite;

    public function __construct()
    {
        $this->announcements = new ArrayCollection();
        $this->favorite = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        //$roles[] = 'ROLE_SUPER_ADMIN';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->Firstname;
    }

    public function setFirstname(string $Firstname): self
    {
        $this->Firstname = $Firstname;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    /**
     * @return Collection|Announcement[]
     */
    public function getAnnouncements(): Collection
    {
        return $this->announcements;
    }

    public function addAnnouncement(Announcement $announcement): self
    {
        if (!$this->announcements->contains($announcement)) {
            $this->announcements[] = $announcement;
            $announcement->setUser($this);
        }

        return $this;
    }

    public function removeAnnouncement(Announcement $announcement): self
    {
        if ($this->announcements->contains($announcement)) {
            $this->announcements->removeElement($announcement);
            // set the owning side to null (unless already changed)
            if ($announcement->getUser() === $this) {
                $announcement->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Announcement[]
     */
    public function getFavorite(): Collection
    {
        return $this->favorite;
    }

    public function addFavorite(Announcement $favorite): self
    {
        if (!$this->favorite->contains($favorite)) {
            $this->favorite[] = $favorite;
        }

        return $this;
    }

    public function removeFavorite(Announcement $favorite): self
    {
        if ($this->favorite->contains($favorite)) {
            $this->favorite->removeElement($favorite);
        }

        return $this;
    }

    public function __toString()
    {
        return (string)$this->Name;
    }
}

src/Form/AnnouncementType.php
<?php

namespace App\Form;

use App\Entity\Announcement;
use App\Entity\Category;
use App\Entity\City;
use App\Repository\CategoryRepository;
use Doctrine\ORM\Mapping\Entity;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AnnouncementType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Name', TextType::class,
                ['label' => false]
            )
            ->add('Price', NumberType::class,
                ['label' => false]
            )
            ->add('Description',TextareaType::class,
                ['label' => false]
            )
            ->add('adress', TextType::class,
                ['label' => false]
            )
            ->add('category', EntityType::class,
                [
                    'class' => Category::class,
                    'label' => false
                ]
            )
            ->add('city', EntityType::class,
                [
                    'class' => City::class,
                    'label' => false
                ]
            )
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Announcement::class,
        ]);
    }
}

src/Controller/AnnouncementController.php
<?php

namespace App\Controller;

use App\Entity\Announcement;
use App\Entity\City;
use App\Form\AnnouncementType;
use App\Form\CityType;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AnnouncementController extends AbstractController
{

    /**
     * @Route("/newAnnouncement", name="newAnnouncement")
     * @param Request $request
     * @return Response
     */
    public function newAnnouncement(Request $request){
        $announcement = new Announcement();
        $city = new City();
        $form = $this->createForm(AnnouncementType::class, $announcement);
        $form->handleRequest($request);
        $user = $this->getUser();
        $cityForm = $this->createForm(CityType::class, $city);
        $cityForm->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()){
            $em = $this->getDoctrine()->getManager();
            $announcement->setUser($user);
            $announcement->setPublishedDate(new \DateTime());
            $em->persist($announcement);
            $em->flush();
            return $this->redirectToRoute('addImages', array('id' => $announcement->getId()));
        }

        if ($cityForm->isSubmitted() && $cityForm->isValid()){
            $em = $this->getDoctrine()->getManager();
            $em->persist($city);
            $em->flush();
        }

        return $this->render('announcement/add.html.twig', [
            'form' => $form->createView(),
            'cityForm' => $cityForm->createView()
        ]);
    }

    /**
     * @Route("/announcement/{id}", name="announcement")
     *
     * @param Announcement $announcement
     * @return Response
     */
    public function announcement(Announcement $announcement) {
        return $this->render('announcement/announcement.html.twig', [
            'announcement' => $announcement
        ]);
    }

    /**
     * @Route("/announcement/{id}/edit", name="editAnnouncement")
     *
     * @param Request $request
     * @param Announcement $announcement
     * @param EntityManagerInterface $manager
     * @return Response
     */
    public function editAnnouncement(Request $request, Announcement $announcement, EntityManagerInterface $manager){
        $form = $this->createForm(AnnouncementType::class, $announcement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $manager->flush();

            return $this->redirectToRoute('announcement', array('id' => $announcement->getId()));
        }

        return $this->render('announcement/edit.html.twig', [
            'form' => $form->createView(),
            'movie' => $announcement
        ]);
    }

    /**
     * @Route("/announcement/{id}/delete", name="deleteAnnouncement")
     *
     * @param Announcement $announcement
     * @param EntityManagerInterface $manager
     * @return RedirectResponse
     */
    public function deleteAnnouncement(Announcement $announcement, EntityManagerInterface $manager){
        foreach($announcement->getPictures() as $picture){
            $manager->remove($picture);
        }
        $manager->remove($announcement);
        $manager->flush();

        return $this->redirectToRoute('home');
    }

}

templates/announcement/add.html.twig
{%  extends 'base.html.twig' %}
{%  block title %}{% endblock %}
{%  block stylesheets %}
    <link rel="stylesheet" href="{{ asset('assets/dropzone/dist/dropzone.css') }}">
{% endblock %}

{%  block body %}
    {{ render(controller('App\\Controller\\HomeController::navBar', {} )) }}

<div class="container mt-5">
    <div class="row">
        <h3 class="ml-3">Add an announcement</h3>
    </div>
</div>
<div class="container mt-3 border p-4">
    {{ form_start(form) }}
            <div class="row">
                <h3 class="ml-3">Your announcement</h3>
            </div>
            <hr/>
            <div class="row">
                <h5 class="ml-3">Categories</h5>
            </div>
            <div class="row">
                <div class="col mt-4 col-md-5">
                    {{ form_row(form.category) }}
                </div>
            </div>
            <div class="row mt-4">
                <h5 class="ml-3">Title</h5>
            </div>
            <div class="row mt-4">
                <div class="col col-md-5">
                    {{ form_row(form.Name) }}
                </div>
            </div>
            <div class="row mt-4">
                <h5 class="ml-3">Description</h5>
            </div>
            <div class="row mt-4">
                <div class="col col-md-5">
                    {{ form_row(form.Description) }}
                </div>
            </div>
            <div class="row mt-4">
                <h5 class="ml-3">Price</h5>
            </div>
            <div class="row mt-4">
                <div class="col col-md-5">
                    {{ form_row(form.Price) }}
                </div>
                <div class="col col-md-1 mt-2 ">
                    <i class="fas fa-euro-sign "></i>
                </div>
            </div>
            <div class="row mt-4">
                <h3 class="ml-3">Location</h3>
            </div>
            <hr/>
            <div class="row mt-4">
                <h5 class="ml-3">City <a data-toggle="modal" data-target="#exampleModal" href="#"><i class="fas fa-plus-circle"></i></a></h5>
            </div>
            <div class="row mt-4">
                <div class="col col-md-5">
                    {{ form_row(form.city) }}
                </div>
            </div>
            <div class="row mt-4">
                <h5 class="ml-3">Address</h5>
            </div>
            <div class="row mt-4">
                <div class="col col-md-5">
                    {{ form_row(form.adress) }}
                </div>
            </div>
                <!--
            <div class="row mt-4">
                <h3 class="ml-3">Images</h3>
            </div>
            <hr/>
            <div class="row mt-4">
                <div class="col ">
                    <div class="alert alert-warning text-center" role="alert">
                       <strong>You can only upload 3 images if you put more it will not work ! </strong>
                    </div>
                    <div class="dropzone" id="my-awesome-dropzone"></div>
                    <div class="alert alert-success text-center mt-4" role="alert">
                        <strong>Image previews :</strong>
                    </div>
                    <div class="dropzone-previews dropzone mt-1"></div>
                </div>
            </div>
            -->
                <div class="row mt-4">
                    <div class="col ">
                        <button class="btn btn-outline-dark mt-2" type="submit">Next Step</button>
                    </div>
                </div>
    {{ form_end(form) }}
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            {{ form_start(cityForm) }}
            <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Add city</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                {{ form_row(cityForm.name) }}
                {{ form_row(cityForm.postalCode, { 'attr' : { 'maxlength': '5', 'minlength': '5'} }) }}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Save changes</button>
            </div>
            {{ form_end(cityForm) }}
        </div>
    </div>
</div>


{% endblock %}

{% block javascripts %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

{% endblock %}

templates/announcement/announcement.html.twig
{%  extends 'base.html.twig' %}
{%  block title %}{% endblock %}
{%  block stylesheets %}
{% endblock %}

{%  block body %}
    {{ render(controller('App\\Controller\\HomeController::navBar', {} )) }}

    <div class="container mt-5 border p-4">
        <div class="row">
            <div class="col-md-8">
                {% if announcement.pictures|length > 0 %}
                    {% if announcement.pictures|length > 1 %}
                    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                        <div class="carousel-inner">
                            {% for picture in announcement.pictures %}
                            {% if loop.first %}
                            <div class="carousel-item active">
                                {% else %}
                                <div class="carousel-item">
                                    {% endif %}
                                    <img class="d-block w-100" src="{{ asset('uploads/images/products/')}}{{picture.image}}" >
                                </div>
                                {% endfor %}
                            </div>
                            <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>
                        {% else %}
                            {% for picture in announcement.pictures %}
                                <img class="img-fluid" src="{{ asset('uploads/images/products/')}}{{picture.image}}">
                            {% endfor %}
                        {% endif %}
                    {% else %}
                        <img class="img-fluid" src="{{ asset('assets/img/no-preview.png')}}">
                    {% endif %}
            </div>
                <div class="col-md-4">
                    <div class="text-center card " style="max-width: 18rem;">
                        <div class="card-header"> <i class="fas fa-user-tie"></i> {{ announcement.user.firstname }} {{ announcement.user.name }} </div>
                        <div class="card-body">
                            <h5 class="card-title"><a href="mailto:{{ announcement.user.email }}">{{ announcement.user.email }}</a></h5>
                            <button class="btn btn-primary btn-lg btn-block" onclick="location.href='{{ path('userProfile', {'id': announcement.user.id } ) }}'">Details <i class="far fa-eye"></i></button>
                        </div>
                    </div>
                </div>
            </div>
        <div class="row">
            <div class="col">
                <h4 class="mt-3">{{ announcement.name }}</h4>
                <h4 class="mt-5">{{ announcement.price }} €</h4>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <h5 class="mt-4">Description :</h5>
                <p class="mt-5" style="white-space: pre-wrap;">{{ announcement.description }}</p>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <h5 class="mt-4">Address :</h5>
                <p class="mt-3"> {{ announcement.city.name }} {{ announcement.city.postalCode }}</p>
                <p class="mt-3"> {{ announcement.adress }}</p>
            </div>
        </div>
        {% if app.user == announcement.user %}
            <div class="row">
                <div class="col">
                    <button class="btn btn-primary btn-lg btn-block" onclick="location.href='{{ path('editAnnouncement', {'id': announcement.id } ) }}'">Edit <i class="far fa-edit"></i></button>
                </div>
                <div class="col">
                <button class="btn btn-warning btn-lg btn-block" onclick="location.href='{{ path('addImages', {'id': announcement.id } ) }}'">Add more Images <i class="fas fa-plus"></i></button>
                </div>
                <div class="col">
                    <button class="btn btn-danger btn-lg btn-block" onclick="location.href='{{ path('deleteAnnouncement', {'id': announcement.id } ) }}'">Delete <i class="far fa-trash-alt"></i></button>
                </div>
            </div>
        {% endif %}

        </div>


{% endblock %}

{% block javascripts %}

{% endblock %}

templates/announcement/edit.html.twig
{%  extends 'base.html.twig' %}
{%  block title %}{% endblock %}
{%  block stylesheets %}
    <link rel="stylesheet" href="{{ asset('assets/dropzone/dist/dropzone.css') }}">
{% endblock %}

{%  block body %}
    {{ render(controller('App\\Controller\\HomeController::navBar', {} )) }}

    <div class="container mt-5">
        <div class="row">
            <h3 class="ml-3">Add an announcement</h3>
        </div>
    </div>
    <div class="container mt-3 border p-4">
        {{ form_start(form) }}
        <div class="row">
            <h3 class="ml-3">Your announcement</h3>
        </div>
        <hr/>
        <div class="row">
            <h5 class="ml-3">Categories</h5>
        </div>
        <div class="row">
            <div class="col mt-4 col-md-5">
                {{ form_row(form.category) }}
            </div>
        </div>
        <div class="row mt-4">
            <h5 class="ml-3">Title</h5>
        </div>
        <div class="row mt-4">
            <div class="col col-md-5">
                {{ form_row(form.Name) }}
            </div>
        </div>
        <div class="row mt-4">
            <h5 class="ml-3">Description</h5>
        </div>
        <div class="row mt-4">
            <div class="col col-md-5">
                {{ form_row(form.Description) }}
            </div>
        </div>
        <div class="row mt-4">
            <h5 class="ml-3">Price</h5>
        </div>
        <div class="row mt-4">
            <div class="col col-md-5">
                {{ form_row(form.Price) }}
            </div>
            <div class="col col-md-1 mt-2 ">
                <i class="fas fa-euro-sign "></i>
            </div>
        </div>
        <div class="row mt-4">
            <h3 class="ml-3">Location</h3>
        </div>
        <hr/>
        <div class="row mt-4">
            <h5 class="ml-3">City</h5>
        </div>
        <div class="row mt-4">
            <div class="col col-md-5">
                {{ form_row(form.city) }}
            </div>
        </div>
        <div class="row mt-4">
            <h5 class="ml-3">Address</h5>
        </div>
        <div class="row mt-4">
            <div class="col col-md-5">
                {{ form_row(form.adress) }}
            </div>
        </div>
        <!--
    <div class="row mt-4">
        <h3 class="ml-3">Images</h3>
    </div>
    <hr/>
    <div class="row mt-4">
        <div class="col ">
            <div class="alert alert-warning text-center" role="alert">
               <strong>You can only upload 3 images if you put more it will not work ! </strong>
            </div>
            <div class="dropzone" id="my-awesome-dropzone"></div>
            <div class="alert alert-success text-center mt-4" role="alert">
                <strong>Image previews :</strong>
            </div>
            <div class="dropzone-previews dropzone mt-1"></div>
        </div>
    </div>
    -->
        <div class="row mt-4">
            <div class="col ">
                <button class="btn btn-outline-dark mt-2" type="submit">Next Step</button>
            </div>
        </div>
        {{ form_end(form) }}
    </div>


{% endblock %}

{% block javascripts %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

{% endblock %}

templates/announcement/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello AnnouncementController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'F:/Ydays/YdaysFakeLeBonCoin/src/Controller/AnnouncementController.php'|file_link(0) }}">src/Controller/AnnouncementController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'F:/Ydays/YdaysFakeLeBonCoin/templates/announcement/index.html.twig'|file_link(0) }}">templates/announcement/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}